// File generated by FlutterFire CLI (iOS Xcode-integration step completed
// manually because this project's Xcode target is `VaultApprover`, not the
// default `Runner`, which the CLI's plist injector assumes).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYgG3Z5kRHoYFaZHfQTi_lv4oW1sPBrEk',
    appId: '1:1048656681718:android:1f9c3ed6531044c3f9aad7',
    messagingSenderId: '1048656681718',
    projectId: 'vaultapprover-ae',
    storageBucket: 'vaultapprover-ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbZOyZSzfKbRNYyTVmMmey_XC4SAVjBMA',
    appId: '1:1048656681718:ios:a0b648158e2ca537f9aad7',
    messagingSenderId: '1048656681718',
    projectId: 'vaultapprover-ae',
    storageBucket: 'vaultapprover-ae.firebasestorage.app',
    iosBundleId: 'com.vaultapprover.app',
  );
}
